[package]
name = "rocs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
lazy_static = "1.4"
once_cell = "1.19"
# rancor = "0.1.0"
# rkyv = "0.8.10"
# rkyv_derive = "0.8.10" 
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
